version: 2.1
orbs:
  cypress: cypress-io/cypress@1.26.0
workflows:
  build:
    jobs:
      - cypress/run:
          yarn: true
          verify-command: yarn cypress verify
          cache-key: 'yarn-packages-{{ arch }}-{{ checksum "yarn.lock" }}'
          command: yarn cypress run --spec cypress/integration/nav.spec.js --env user=$user,password=$password --record --key 4fdf694e-31ef-413c-9d67-ca61c211c391
          parallel: true
          parallelism: 2
          group: 2 machines