version: 2.1
orbs:
  cypress: cypress-io/cypress@1
executors:
  base10-user-password:
    environment:
      user: $user
      password: $password
workflows:
  build:
    jobs:
      - cypress/run:
          executor: base10-user-password
          name: cypress slack
          yarn: true
          cache-key: 'yarn-packages-{{ arch }}-{{ checksum "yarn.lock" }}'
          command: yarn test
          browser: chrome
          parallel: true
          parallelism: 2
          group: 2 machines
    
          