version: 2.1
orbs:
  cypress: cypress-io/cypress@1
executors:
  base10-user-password:
    docker:
      - image: 'cypress/base:10'
    environment:
      user: $user
      password: $password
workflows:
  build:
    jobs:
      - cypress/run:
          command: yarn install
      - cypress/run:
          name: cypress slack
          yarn: true
          executor: base10-user-password
          command: yarn test
          browser: chrome