version: 2.1
orbs:
  cypress: cypress-io/cypress@1.26.0
workflows:
  build:
    jobs:
      - cypress/run:
          yarn: true
          verify-command: yarn cypress verify
          cache-key: 'yarn-packages-{{ arch }}-{{ checksum "yarn.lock" }}'
          command: yarn test --env user:$user, password:$password